using MusicPlayerApp.Models;
using MusicPlayerApp.Repository;


namespace MusicPlayerApp.Service
{
    // Business Layer Class That Provides Playlist Functionality
    class PlaylistService : IPlaylistService
    {
        private readonly IPlaylistRepository _repository;
        private List<Playlist> loadedPlaylists;
        public PlaylistService(IPlaylistRepository repository) {
            _repository = repository;

            // Loads the auto generated number
            Playlist.lastAutoGeneratedNumber = _repository.LoadAutoGeneratedNumber();
        }

        public List<Playlist> GetPlaylists()
        {
            if (loadedPlaylists == null)
                RefreshPlaylistsData();

            return loadedPlaylists?? new List<Playlist>();
        }

        public async Task CreatePlaylistAsync()
        {
            if (loadedPlaylists == null)
                loadedPlaylists = new List<Playlist>();

            loadedPlaylists.Add(new Playlist(true));
            _repository.SaveAutoGeneratedNumber(Playlist.lastAutoGeneratedNumber);

            bool taskResult = await _repository.SavePlaylistsToFile(loadedPlaylists);
            if (taskResult) {
                RefreshPlaylistsData();
            }
        }

        public async Task DeletePlaylistAsync(string id)
        {
            Playlist? playlist = loadedPlaylists
                .FirstOrDefault(playlist => playlist.id == id);

            if (playlist != null && loadedPlaylists.Count > 0 && loadedPlaylists.Contains(playlist))
                loadedPlaylists.Remove(playlist);
            else
                return;

            bool taskResult = await _repository.SavePlaylistsToFile(loadedPlaylists);
            if (taskResult)
            {
                RefreshPlaylistsData();
            }
        }

        public void RefreshPlaylistsData()
        {
            List<Playlist> playlists = _repository.LoadPlaylistFromFile();

            if(playlists == null || playlists.Count <= 0)
                return;

            this.loadedPlaylists = playlists;
        }

        public void RenamePlaylist(string guid, string newName)
        {
            throw new NotImplementedException();
        }
    }
}
