using MusicPlayerApp.Models;
using MusicPlayerApp.Repository;
#pragma warning disable CS8603

namespace MusicPlayerApp.Service
{
    // Business Layer Class That Provides Playlist Functionality
    class PlaylistService : IPlaylistService
    {
        private readonly IPlaylistRepository _repository;
        private List<Playlist> loadedPlaylists;
        public PlaylistService(IPlaylistRepository repository) {
            _repository = repository;

            // Loads the auto generated number
            Playlist.lastAutoGeneratedNumber = _repository.LoadAutoGeneratedNumber();
        }

        public List<Playlist> GetPlaylists()
        {
            if (loadedPlaylists == null)
                RefreshPlaylistsData();

            return loadedPlaylists?? new List<Playlist>();
        }

        public async Task CreatePlaylistAsync()
        {
            if (loadedPlaylists == null)
                loadedPlaylists = new List<Playlist>();

            loadedPlaylists.Add(new Playlist(true));
            _repository.SaveAutoGeneratedNumber(Playlist.lastAutoGeneratedNumber);

            bool taskResult = await _repository.SavePlaylistsToFile(loadedPlaylists);
            if (taskResult) {
                RefreshPlaylistsData();
            }
        }

        public async Task DeletePlaylistAsync(string id)
        {
            Playlist playlist = GetPlaylistById(id);

            if (playlist != null && loadedPlaylists.Count > 0 && loadedPlaylists.Contains(playlist))
                loadedPlaylists.Remove(playlist);
            else
                return;

            bool taskResult = await _repository.SavePlaylistsToFile(loadedPlaylists);
            if (taskResult)
            {
                RefreshPlaylistsData();
            }
        }

        public void RefreshPlaylistsData()
        {
            List<Playlist> playlists = _repository.LoadPlaylistFromFile();

            if(playlists == null || playlists.Count <= 0)
                return;

            this.loadedPlaylists = playlists;
        }

        public void RenamePlaylist(string guid, string newName)
        {
            throw new NotImplementedException();
        }

        public List<string> GetMusicTrackIdsFromPlaylistId(string id)
        {
            Playlist playlist = GetPlaylistById(id);

            if(playlist != null)
                return playlist.trackIds;

            return null;
        }

        private Playlist GetPlaylistById(string id)
        {

            return loadedPlaylists
        .FirstOrDefault(p => p.id == id);
        }

        public void AddMusicTrackToPlaylistId(string playlistId, string trackId)
        {
            Playlist playlist = GetPlaylistById(playlistId);

            if(playlist != null && !playlist.trackIds.Contains(trackId))
                playlist.trackIds.Add(trackId);

            _repository.SavePlaylistsToFile(loadedPlaylists);
        }
    }
}
