using MusicPlayerApp.Models;
using System.Text.Json;
using System.Threading.Tasks;

namespace MusicPlayerApp.Repository
{
    internal class PlaylistRepository : IPlaylistRepository
    {
        private readonly string _dataAbsolutePath;
        private readonly string _playlistsAbsolutePath;
        private readonly string _configAbsolutePath;
        public PlaylistRepository()
        {
            _dataAbsolutePath = Path.Combine(
                Directory.GetParent(AppDomain.CurrentDomain.BaseDirectory).Parent.Parent.Parent.FullName,
                "Data"
            );

            _playlistsAbsolutePath = Path.Combine(
                _dataAbsolutePath,
                "playlists.json"
            );

            _configAbsolutePath = Path.Combine(
                _dataAbsolutePath,
                "config.txt"
            );
        }
        public List<Playlist> LoadPlaylistFromFile()
        {
            try
            {
                string jsonText = File.ReadAllText(_playlistsAbsolutePath);

                List<Playlist> playlists = JsonSerializer.Deserialize<List<Playlist>>(jsonText);

                return playlists;
            }
            catch (FileNotFoundException exc) {
                File.Create(_playlistsAbsolutePath);

                return null;
            }
            catch (Exception exc)
            {
                return null;
            }
        }

        public async Task<bool> SavePlaylistsToFile(List<Playlist> playlists)
        {
            try
            {
                string jsonText = JsonSerializer.Serialize(playlists, new JsonSerializerOptions {WriteIndented = true});

                await File.WriteAllTextAsync(_playlistsAbsolutePath, jsonText);
                return true;
            }
            catch (Exception exc)
            {
                return false;
            }
        }

        public int LoadAutoGeneratedNumber()
        {
            try
            {
                string text = File.ReadAllText(_configAbsolutePath);

                return int.Parse(text);
            } 
            catch (Exception e)
            {
                SaveAutoGeneratedNumber(1);
                return 1;
            }
        }

        public void SaveAutoGeneratedNumber(int value)
        {
            try
            {
                File.WriteAllText(_configAbsolutePath, value.ToString());
            }
            catch (Exception e) { }
        }
    }
}
