
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Windows.Forms.VisualStyles;

namespace MusicPlayerApp.Models
{
    public class Playlist
    {
        [JsonInclude]
        public string id { get; set; }
        [JsonInclude]
        public string description { get; set; }
        [JsonInclude]
        public string playlistName { get; set; }
        public static int lastAutoGeneratedNumber { get; set; }
        [JsonInclude]
        public List<string> trackIds { get; set; }

        // Constructor is used for new playlist creation.
        public Playlist(bool shouldCreateNew) {
            if (shouldCreateNew)
            {
                this.id = Guid.NewGuid().ToString();
                this.playlistName = "Playlist No " + Convert.ToString(lastAutoGeneratedNumber++);
                this.description = "";
                this.trackIds = new List<string>();
            }
        }

        // Constructed is used for json serialization/deserialization.
        [JsonConstructor]
        public Playlist() { }
        public string GetName()
        {
            return this.playlistName;
        }
    }
}
