
using System.Text.Json;
using System.Windows.Forms.VisualStyles;

namespace MusicPlayerApp.Models
{
    internal class Playlist
    {
        private string id { get; }
        private string description { get; set; }
        private string playlistName { get; set; }

        private static int lastAutoGeneratedNumber { get; set; }
        private List<string> trackIds;

        public Playlist(string playlistName) {
            this.id = Guid.NewGuid().ToString();
            this.playlistName = playlistName;
        }

        public Playlist()
        {
            this.id = Guid.NewGuid().ToString();
            this.playlistName = "Track No" + Convert.ToString(lastAutoGeneratedNumber++);
        }
        public void AddTrack(string trackId)
        {
            trackIds.Add(trackId);
        }
        public bool RemoveTrack(string trackId) {
            return trackIds.Remove(trackId);
        }
        public bool HasTrack(string trackId)
        {
            return trackIds.Contains(trackId);
        }
    }
}
